server:
  port: 8888
spring:
  main:
    allow-circular-references: true
  application:
    name: AICustomer
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/aicustomer?useSSL=false&serverTimezone=UTC
      username: root
      password: root
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#      resolve-lazily: true
#      in-memory-threshold: 10MB
mybatis-plus:
  type-aliases-package: com.young.aicustomer.entity
logging:
  level:
    com.young.aicustomer: debug

xunfei:
  url: https://spark-api.xf-yun.com/v2.1/chat
  appId: 79b98775
  apiSecret: MDA2YmNkYjBhOWM5YzNiOTc5MzUwNGMw
  apiKey: 76f2e2926708e525fbc8841a7ba1b0e1
  maxResponseTime: 30    # 最大响应时间，单位：秒